version: '3.7'

services:
  database_pg:
    image: postgres
    container_name: database_pg
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker-pg
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links: 
      - database_pg
    depends_on: 
      - database_pg

volumes:
  pgdata:
    driver: local